// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Meus Descontos Online — Promoções e Ofertas",
  description: "Links rápidos para promoções da Amazon, Mercado Livre, Magazine Luiza, Americanas, Shopee e AliExpress.",
  keywords: "promoções Shopee, descontos Amazon, ofertas Mercado Livre, cupons AliExpress, Magazine Luiza promoções, Americanas ofertas",
  openGraph: {
    title: "Meus Descontos Online — Promoções e Ofertas",
    description: "Links rápidos para promoções da Amazon, Mercado Livre, Magazine Luiza, Americanas, Shopee e AliExpress.",
    type: "website",
    locale: "pt_BR",
    siteName: "Meus Descontos Online",
  },
  twitter: {
    card: "summary_large_image",
    title: "Meus Descontos Online — Promoções e Ofertas",
    description: "Links rápidos para promoções da Amazon, Mercado Livre, Magazine Luiza, Americanas, Shopee e AliExpress.",
  },
  robots: {
    index: true,
    follow: true,
  },
  viewport: "width=device-width, initial-scale=1",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}